name: mobilution
favicon: null
layout_spectrum: 0.39589
typography_spectrum: 0.1635482197161764
title: mobilution.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1f24'
    - '#112233'
    - '#ffffff'
    - '#969696'
    - '#5e5e5e'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
