name: mobilution
favicon: null
layout_spectrum: 0.6348809332121164
typography_spectrum: 0.1635482197161764
title: mobilution.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6110816190484911
  lightness: 0.10442280676215887
  saturation: 0.16201474564149976
  rhythmicContrast: 0.30195937282405794
purpose: []
